### ISSUE TITLE
Wrong countdown

### ISSUE THREAD

**Issue by MonteePoke** [illiusterka/poe2_countdown#1]
Right now countdown displays time until start of June 7th in user's system timezone
Which means different users can see different time
Also leagues usually start at 7 or 8 PM GMT

Proposed change 
`new Date("Jun 7, 2024 00:00:00").getTime();`
To
`new Date("Jun 7, 2024 20:00:00Z").getTime();`

**Comment by illiusterka** [comment]
nice catch man
